apiVersion: apps/v1
kind: Deployment
metadata:
  name: valhalla
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: valhalla
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valhalla
    spec:
      containers:
        - name: valhalla
          image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
          ports:
            - containerPort: 8002
          env:
            - name: serve_tiles
              value: "True"
            - name: use_tiles_ignore_pbf
              value: "True"
            - name: build_admins
              value: "False"
            - name: build_elevation
              value: "False"
            - name: force_rebuild
              value: "False"
            - name: server_threads
              value: "8"
          volumeMounts:
            - name: valhalla-tiles
              mountPath: /custom_files
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
            limits:
              memory: "16Gi"
              cpu: "4"
      volumes:
        - name: valhalla-tiles
          persistentVolumeClaim:
            claimName: valhalla-tiles-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: valhalla
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valhalla
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
