apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  labels:
    app: ollama
    app.kubernetes.io/part-of: civpulse-geo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
