apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass-zfs-local.yaml
  - pv-osm-pbf.yaml
  - pv-nominatim-data.yaml
  - pv-osm-tile-data.yaml
  - pv-valhalla-tiles.yaml
  - pv-tiger-data-dev.yaml
  - pv-tiger-data-prod.yaml
