apiVersion: v1
kind: Service
metadata:
  name: geo-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: geo-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
